services:
  - type: web
    name: hrf-newsletter-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: MAILCHIMP_API_KEY
        sync: false
      - key: MAILCHIMP_SERVER_PREFIX
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: SECRET_KEY
        generateValue: true